article_module/urls.py
from django.urls import path

from article_module import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='articles_list'),
    path('cat/<str:category>', views.ArticleListView.as_view(), name='articles_by_category_list'),
    path('add-article-comment', views.add_article_comment, name='add_article_comment'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='articles_detail'),
]

e_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('order/', include('order_module.urls')),
    path('user/', include('user_panel_module.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/models.py
from django.db import models
from jalali_date import datetime2jalali, date2jalali
from account_module.models import User


# Create your models here.

class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, blank=True, verbose_name='دسته بندی والد',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, verbose_name='عنوان در url', unique=True)
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات مقاله')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='نویسنده', editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def get_jalali_create_date(self):
        return date2jalali(self.create_date)

    def get_jalali_create_time(self):
        return self.create_date.strftime('%H:%M')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return self.title


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComment', on_delete=models.CASCADE, null=True, blank=True, verbose_name='والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن نظر')

    class Meta:
        verbose_name = "نظر مقاله"
        verbose_name_plural = "نظرات مقاله"

    def __str__(self):
        return self.text

article_module/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView
from article_module.models import Article, ArticleCategory, ArticleComment
from django.utils.encoding import force_str


# Create your views here.

class ArticleListView(ListView):
    template_name = 'article_module/article_page.html'
    model = Article
    paginate_by = 5

    def get_queryset(self):
        query = super(ArticleListView, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
        return query


def article_categories_component(request: HttpRequest):
    article_main_categories = ArticleCategory.objects.prefetch_related('articlecategory_set').filter(is_active=True,
                                                                                                     parent_id=None)
    context = {
        'main_categories': article_main_categories
    }
    return render(request, 'article_module/components/article_categories_component.html', context)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detail_page.html'

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data()
        article: Article = kwargs.get('object')
        context['comments'] = ArticleComment.objects.filter(article_id=article.id, parent=None).order_by(
            '-create_date').prefetch_related(
            'articlecomment_set')
        context['comments_count'] = ArticleComment.objects.filter(article_id=article.id).count()

        return context


def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated:
        request.encoding = 'utf-8'
        article_id = request.POST.get('article_id')
        article_comment = request.POST.get('article_comment')
        parent_id = request.POST.get('parent_id')

        new_comment = ArticleComment(article_id=article_id, text=article_comment, user_id=request.user.id,
                                     parent_id=parent_id)
        new_comment.save()
        context = {
            'comments': ArticleComment.objects.filter(article_id=article_id, parent=None).order_by(
                '-create_date').prefetch_related('articlecomment_set'),
            'comments_count': ArticleComment.objects.filter(article_id=article_id).count()
        }

        return render(request, 'article_module/includes/article_comments_partial.html', context)

    return HttpResponse('response')

article_module/templates/article_module/article_detail_page.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% load poll_extras %}
{% load thumbnail %}

{% block title %}
    جزییات مقاله
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">{{ article.title }}</h2>
                        <div class="single-blog-post">
                            <h3>{{ article.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    {% if article.author is not None %}
                                        <li><i class="fa fa-user"></i> {{ article.author }}</li>
                                    {% endif %}
                                    <li><i class="fa fa-clock-o"></i>{{ article.get_jalali_create_time }}</li>
                                    <li><i class="fa fa-calendar"></i>{{ article.create_date | show_jalali_date }}
                                    </li>
                                </ul>
                                <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                            </div>
                            <a href="">
                                {% thumbnail article.image "862x398" quality=95 crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                            </a>
                            <p>
                                {{ article.short_description }}
                            </p>
                            <p>
                                {{ article.text }}
                            </p>
                        </div>
                    </div><!--/blog-post-area-->


                    {% if article.author %}
                        <div class="media commnets">
                            <a class="pull-right" href="#">
                                {% if article.author.avatar %}
                                    {% thumbnail article.author.avatar "121x86" quality=95 crop='center' as im %}
                                        <img class="media-object" src="{{ im.url }}">
                                    {% endthumbnail %}
                                {% else %}
                                    <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                {% endif %}
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">نویسنده : {{ article.author }}</h4>
                                <p>
                                    {{ article.author.about_user }}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                    <!--Comments-->
                    <div class="col-sm-12" id="reviews">
                        <div class="response-area" id="article_comments_area">
                            <h2> نظرات ({{ comments_count }})</h2>
                            <ul class="media-list">
                                {% for comment in comments %}
                                    <li class="media" id="single_article_comment_box_{{ comment.id }}">
                                        <a class="pull-right" href="#">
                                            <img class="media-object" src="/static/images/blog/user.png" alt="">
                                        </a>
                                        <div class="media-body">
                                            <ul class="sinlge-post-meta">
                                                <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                                <li><i class="fa fa-clock-o"></i> {{ comment.create_date | time }}</li>
                                                <li>
                                                    <i class="fa fa-calendar"></i> {{ comment.create_date|show_jalali_date }}
                                                </li>
                                            </ul>
                                            <p>
                                                {{ comment.text }}
                                            </p>
                                            <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                                                    class="fa fa-reply"></i>پاسـخ</a>
                                        </div>
                                    </li>

                                    {% for sub_comment in comment.articlecomment_set.all %}
                                        <li class="media second-media" id="single_article_comment_box_{{ comment.id }}">
                                            <a class="pull-right" href="#">
                                                <img class="media-object" src="/static/images/blog/user.png" alt="">
                                            </a>
                                            <div class="media-body">
                                                <ul class="sinlge-post-meta">
                                                    <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                                    <li><i class="fa fa-clock-o"></i> {{ sub_comment.create_date | time }}
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-calendar"></i> {{ sub_comment.create_date|show_jalali_date }}
                                                    </li>
                                                </ul>
                                                <p>
                                                    {{ sub_comment.text }}
                                                </p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                {% endfor %}

                            </ul>
                        </div><!--/Response-area-->
                        <div class="replay-box" >
                            {% if request.user.is_authenticated %}
                                <div class="row">
                                    <div class="col-sm-12" id="article_comment_form">
                                        <h2>نظـر خود را بنویسیـد</h2>

                                        <input type="hidden" value="{{ article.id }}"
                                               id="article_comment_id">
                                        <input type="hidden" value="" id="article_comment_parent_id">
                                        {% csrf_token %}
                                        <div class="text-area">
                                            <div class="blank-arrow">
                                                <label for="article_comment_text">متن پیام</label>
                                            </div>
                                            <span>*</span>
                                            <textarea name="message" rows="11"
                                                      id="article_comment_text"></textarea>
                                            <button type="submit" class="btn btn-primary"
                                                    id="submit_article_comment">
                                                ارسـال نظـر
                                            </button>
                                            <input type="hidden" id="article-csrf-token" value="{% csrf_token %}">
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <div class="alert alert-warning">
                                    برای درج نظر می بایست <a href="{% url 'login_page' %}">لاگین</a> کنید
                                </div>
                            {% endif %}
                        </div><!--/Repaly Box-->
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'article_module.views.article_categories_component' %}
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

article_module/templates/article_module/article_page.html
{% extends 'shared/_layout.html' %}
{% load static %}
{% load poll_extras %}
{% load thumbnail %}
{% load render_partial %}
{% block page_title %}
    لیست مقالات
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">

            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">آخریـن اخبـار</h2>
                    {% for article in article_list %}
                        <div class="single-blog-post">
                            <h3>{{ article.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    {% if article.author is not None %}
                                        <li><i class="fa fa-user"></i>{{ article.author }}</li>
                                    {% endif %}
                                    <li><i class="fa fa-clock-o"></i> {{ article.get_jalali_create_time }}</li>
                                    <li><i class="fa fa-calendar"></i> {{ article.create_date | show_jalali_date }}</li>
                                </ul>
                                <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                            </div>
                            <a href="">
                                {% thumbnail article.image "862x398" quality=95 crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                            </a>
                            <p>{{ article.short_description }}</p>
                            <a class="btn btn-primary" href="{% url 'articles_detail' pk=article.id %}">ادامـه مطلب</a>
                        </div>
                    {% endfor %}
                    <div class="pagination-area">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for pageNumber in paginator.page_range %}
                                <li class="{% if page_obj.number == pageNumber %} active {% endif %}">
                                    <a href="?page={{ pageNumber }}">{{ pageNumber }}</a>
                                </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="left-sidebar">

                    {% render_partial 'article_module.views.article_categories_component' %}

                    <div class="shipping text-center"><!--shipping-->
                        <img src="{% static 'images/blog/Blue_Digital_Marketing_Methods_Facebook_Ad.png' %}" width="250"
                             height="250" alt="">
                    </div><!--/shipping-->

                </div>
            </div>

        </div>
    </div>
{% endblock %}